### ISSUE TITLE
Exits - vue de détail

### ISSUE THREAD

**Issue by EmmanuelleAllain** [WildCodeSchool/2022_03_PHP_Lyon_Base_things#55]
Dans le détail de chaque exit, dans le paragraphe "remarques", il y a juste des numéros de remarque : "remarque 8", "remarque 7".
Exemple sur Aiguillette st michel et Bambi.

**Comment by Anthony-AGTN** [comment]
Oui, on a une US "Ajouter un jeu de données" à faire encore. ^^

**Comment by Anthony-AGTN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RESSOURCES | Ajouter un jeu de données.](https://trello.com/c/6MZfsle3/72-ressources-ajouter-un-jeu-de-donn%C3%A9es)
