### ISSUE TITLE
Exits - upload d'image (vide)

### ISSUE THREAD

**Issue by ghartemann** [WildCodeSchool/2022_03_PHP_Lyon_Base_things#56]
Affiche un lien mort vers une image quand pas d'image choisie à l'upload
<img width="935" alt="Capture d’écran 2022-05-09 à 10 16 18" src="https://user-images.githubusercontent.com/36921636/167368809-0b1836d7-a118-4369-bc2c-90ac5ef185d6.png">

**Comment by Anthony-AGTN** [comment]
C'est lors de l'ajout ou de la modification ? "Je suppose que c'est l'ajout ^^ "

**Comment by Anthony-AGTN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EXITS | upload d'image (vide)](https://trello.com/c/4kYuh1MF/73-exits-upload-dimage-vide)
