### ISSUE TITLE
Formulaire "ajouter un saut"

### ISSUE THREAD

**Issue by EmmanuelleAllain** [WildCodeSchool/2022_03_PHP_Lyon_Base_things#58]
- Dans les coordonnées GPS, il est possible de rentrer autre chose qu'un url, notamment du texte, idem pour la vidéo.
- On peut mettre une hauteur de type texte ou une hauteur de 1 m.
- Quand on arrive sur le formulaire on ne sait pas quels sont les champs obligatoires, ça pourrait être pas mal de les mettre en relief (soit avec une couleur différente, soit avec un astérisque). Quand on ne remplit aucun champ, il n'y a que le message du type de champ obligatoire qui apparait, ce serait bien d'afficher tous les messages d'erreur de champs vides.

**Comment by Anthony-AGTN** [comment]
- Dans les coordonnées GPS, il est possible de rentrer autre chose qu'un url, notamment du texte, idem pour la vidéo.
ANTHONY >>> (Dans l'ajout d'un exit on vient renseigner des coordonnées, pas une url directement. Donc c'est bon pour cette partie, c'est le comportement normal.)


- On peut mettre une hauteur de type texte ou une hauteur de 1 m.
ANTHONY >>> (Dans l'ajout d'un exit on ne demande pas forcement un float ou un INT, les personnes peuvent être amenée à renseigner une chaine de caractère comme "Entre 220m et 2000m!!" par exemple. C'est donc ok pour ce cas là.)


- Quand on arrive sur le formulaire on ne sait pas quels sont les champs obligatoires, ça pourrait être pas mal de les mettre en relief (soit avec une couleur différente, soit avec un astérisque). Quand on ne remplit aucun champ, il n'y a que le message du type de champ obligatoire qui apparaît, ce serait bien d'afficher tous les messages d'erreur de champs vides.
ANTHONY >>> (Pour cette partie, les commentaires sont pertinents, j'ai créé un ticket dans Trello)

**Comment by Anthony-AGTN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SAUT | Formulaire "ajouter un saut"](https://trello.com/c/GvEeXToO/75-saut-formulaire-ajouter-un-saut)

**Comment by Alphapwned** [comment]
Fixed
