### ISSUE TITLE
Exits - impossibilité de supprimer un lieu

### ISSUE THREAD

**Issue by ghartemann** [WildCodeSchool/2022_03_PHP_Lyon_Base_things#59]
Quand on supprime un lieu, il ne disparaît pas de la BDD et est uniquement masqué. C'est un choix je suppose puisque vous avez une méthode hide.

Deux problèmes :
- on peut toujours accéder à un lieu via le saut qui y est relié ;
- quand on utilise un filtre, les lieux réapparaissent

**Comment by Anthony-AGTN** [comment]
on peut toujours accéder à un lieu via le saut qui y est relié ; 
ANTHONY>>> ça c'est bon, c'est le comportement voulu.

quand on utilise un filtre, les lieux réapparaissent 
ANTHONY >>> ça en revanche ce n'est pas voulu du tout ^^

**Comment by Anthony-AGTN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EXIT | Les exits déactivés réapparaisse lors de l'utilisation d'un filtre.](https://trello.com/c/Wi0o5xI6/76-exit-les-exits-d%C3%A9activ%C3%A9s-r%C3%A9apparaisse-lors-de-lutilisation-dun-filtre)

**Comment by Alphapwned** [comment]
Issue fixed
