### ISSUE TITLE
bouton créer un compte

### ISSUE THREAD

**Issue by EmmanuelleAllain** [WildCodeSchool/2022_03_PHP_Lyon_Base_things#61]
Ce bouton ne marche pas... A supprimer s'il ne sert à rien ;)

**Comment by Anthony-AGTN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [USER | Bouton créer un compte](https://trello.com/c/FMp1CIWc/78-user-bouton-cr%C3%A9er-un-compte)
