### ISSUE TITLE
Pas de redirection si on entre l'url d'édition sans être connecté

### ISSUE THREAD

**Issue by ghartemann** [WildCodeSchool/2022_03_PHP_Lyon_Base_things#62]
On arrive sur une page blanche avec un conteneur vide

<img width="737" alt="Capture d’écran 2022-05-09 à 10 45 11" src="https://user-images.githubusercontent.com/36921636/167373851-2b43531c-8ff4-46a8-a0e8-ef5d91cd385b.png">

**Comment by Anthony-AGTN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EXIT | Pas de redirection si on entre l'url d'édition sans être connecté](https://trello.com/c/6DjyR8Sk/79-exit-pas-de-redirection-si-on-entre-lurl-d%C3%A9dition-sans-%C3%AAtre-connect%C3%A9)
