### ISSUE TITLE
Suppression d'exit

### ISSUE THREAD

**Issue by EmmanuelleAllain** [WildCodeSchool/2022_03_PHP_Lyon_Base_things#63]
Quand on supprime un exit, on peut encore y accéder via l'url détaillée : http://localhost:8000/exits/show?id=2

**Comment by Anthony-AGTN** [comment]
Effectivement, les exits doivent toujours être disponible via les carnets de saut, c'est pour ça que l'on peut toujours y accéder même après "suppression". Maintenant que j'y pense nous aurions peut-être du appeler ce bouton désactivation au lieu de suppression.

**Comment by Anthony-AGTN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [EXIT | Suppression d'exit](https://trello.com/c/lgGSoUF2/80-exit-suppression-dexit)
