### ISSUE TITLE
Formulaire "ajouter un saut"

### ISSUE THREAD

**Issue by EmmanuelleAllain** [WildCodeSchool/2022_03_PHP_Lyon_Base_things#64]
- On peut ajouter une date ancienne, type 1222
- On peut mettre autre chose qu'un url dans le lien de la vidéo

**Comment by Anthony-AGTN** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SAUT | Formulaire "ajouter un saut"](https://trello.com/c/unbqMzlr/81-saut-formulaire-ajouter-un-saut)
